#! /bin/sh

sxhkd &

bspc monitor -d >_ 


feh --bg-fill ~/bspolyrice2/bg.JPG &

compton compton --config ~/bspolyrice2/compton.conf &

polybar example &

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color		"#000000"
bspc config active_border_color		"#ffffff"
bspc config focused_border_color	"#ffffff"
bspc config presel_feedback_color	"#000000"
